package com.carrene.restfulpy.client;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'perfect' at '10/8/17 2:19 PM' with Gradle 2.10
 *
 * @author perfect, @date 10/8/17 2:19 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
